receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  filter/healthcheck:
    traces:
        span:
          - 'attributes["http.target"] == "/healthcheck"'
  redaction/creditcard:
    allow_all_keys: true
    blocked_values:
      - "4[0-9]{12}(?:[0-9]{3})?" ## Visa credit card number
      - "(5[1-5][0-9]{14})"       ## MasterCard number

exporters:
  logging:
  otlp:
    endpoint: "jaeger:4317"
    tls:
        insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,filter/healthcheck,redaction/creditcard]
      exporters: [otlp,logging]

