receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  filter/healthcheck:
    spans:
      exclude:
        match_type: strict
        attributes:
          - Key: http.target
            Value: /health

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
        insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,filter/healthcheck]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]

