receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  filter/healthcheck:
    traces:
        span:
          - 'attributes["http.target"] == "/healthcheck"'

exporters:
  logging:
  otlp:
    endpoint: "jaeger:4317"
    tls:
        insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,filter/healthcheck]
      exporters: [otlp,logging]

